---
- name: 'Install system dependencies'
  apt:
    name: ['mysql-server-5.6', 'python-mysqldb']
    state: latest
  become: yes

- name: 'Create a MySQL database'
  mysql_db:
    name: '{{ wp_db_name }}'
    login_user: root
    state: present

- name: 'Create MySQL user'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
    host: '{{ item }}'
  with_items:
    - '{{ wp_host_ip }}'

- name: 'Set MySQL to accept all connections'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql
