IMAGE_NAME = "ubuntu/trusty64"
N = 1

Vagrant.configure("2") do |config|

  config.vm.define "k8s-master" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network "private_network", ip: "172.17.177.40"
    master.vm.hostname = "k8s-master"
    master.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
        node.vm.box = IMAGE_NAME
        node.vm.network "private_network", ip: "172.17.177.#{i + 40}"
        node.vm.hostname = "node-#{i}"
        node.vm.provider "virtualbox" do |v|
          v.memory = 1024
          v.cpus = 1
        end
    end
  end

end
